#=============================================================================
# <copyright>
# Copyright (c) 2024 3LC Inc. All rights reserved.
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written permission of the copyright owner.
# </copyright>
#=============================================================================


dashboard:
  # tlc-enterprise-dashboard is the name used in docker-compose when building the docker image. Change according to the desired name in container registry.
  image: "{{ .Values.global.containerRegistry }}tlc-enterprise-dashboard:{{ .Values.global.imageTag }}"
  objectServiceUrl: "http://{{ .Values.global.dnsName }}/api"
  objectServiceAuthSecret: "{{ .Values.global.objectServiceAuthSecret }}"

object-service:
  # tlc-enterprise-object-service is the name used in docker-compose when building the docker image. Change according to the desired name in container registry.
  image: "{{ .Values.global.containerRegistry }}tlc-enterprise-object-service:{{ .Values.global.imageTag }}"
  licenseKey: "{{ .Values.global.licenseKey }}"
  objectServiceAuthSecret: "{{ .Values.global.objectServiceAuthSecret }}"
  pvc_host_path: "{{ .Values.global.pvc_host_path }}"

compute-service:
  # tlc-enterprise-compute-service is the name used in docker-compose when building the docker image. Change according to the desired name in container registry.
  image: "{{ .Values.global.containerRegistry }}tlc-enterprise-compute-service:{{ .Values.global.imageTag }}"
  licenseKey: "{{ .Values.global.licenseKey }}"
  objectServiceAuthSecret: "{{ .Values.global.objectServiceAuthSecret }}"
  pvc_host_path: "{{ .Values.global.pvc_host_path }}"

nginx:
  service:
    type: NodePort

  # Everything after / is passed to the Dashboard by default, e.g. /index.html -> dashboard:8080/index.html.
  # For the Object Service, everything after /api is passed, e.g. /api/live -> object-service:5015/live.
  # Thus, the trailing slash in both the location and proxy_pass is important.
  serverBlock: |-
    server {
      listen 0.0.0.0:8080;
      location / {
        proxy_pass http://{{ .Release.Name }}-dashboard:8080/;
        proxy_redirect     off;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      
      location /api/ {
        proxy_pass http://{{ .Release.Name }}-object-service:5015/;
        proxy_redirect     off;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /compute/ {
        proxy_pass http://{{ .Release.Name }}-compute-service:5020/;
        proxy_redirect     off;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }



# Global configuration
global:
  # Docker registry URI
  containerRegistry: #

  # Image tag to use to pull from registry
  imageTag: #

  # Service DNS name, like "tlc.mydomain.com"
  dnsName: #

  # The cryptlex license key from 3LC
  licenseKey: #

  # The Object Service authentication secret
  objectServiceAuthSecret: #

  # Where the 3LC projects are on the host machine
  pvc_host_path: #


