#=============================================================================
# <copyright>
# Copyright (c) 2026 3LC Inc. All rights reserved.
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written permission of the copyright owner.
# </copyright>
#=============================================================================
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  tls.crt: {{ required "nginx: tls.crt is required when tls.enabled" .Values.tls.crt | b64enc }}
  tls.key: {{ required "nginx: tls.key is required when tls.enabled" .Values.tls.key | b64enc }}
{{- end }}
