#=============================================================================
# <copyright>
# Copyright (c) 2024 3LC Inc. All rights reserved.
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written permission of the copyright owner.
# </copyright>
#=============================================================================
apiVersion: v1
appVersion: "1.0"
description: Reverse proxy providing a single entry point to the 3LC services
name: nginx
version: 0.1.0
