#=============================================================================
# <copyright>
# Copyright (c) 2024 3LC Inc. All rights reserved.
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written permission of the copyright owner.
# </copyright>
#=============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: "{{- tpl .Values.image . }}"
          imagePullPolicy: {{ tpl .Values.imagePullPolicy . }}
          volumeMounts:
            - name: my-volume
              mountPath: /data
          ports:
            - name: http-server
              containerPort: {{ required "required" .Values.servicePort }}
          livenessProbe:
            httpGet:
              # The Object Service exposes /live, which can be used by for checking reachability without authorization
              path: /live
              port: http-server
            initialDelaySeconds: 60
            timeoutSeconds: 20
            failureThreshold: 6
          env:
            # TLC_LICENSE is required for 3LC to run when deployed in enterprise settings. This should be the value of the cryptlex license key provided from 3LC.
            # This can also be configured as a Kubernetes secret for more security. For the sake of the demo, a Kubernetes secret is not used.
            # See also: https://docs.3lc.ai/3lc/latest/getting-started/deployment-options/enterprise-on-prem/licensing.html
            - name: TLC_LICENSE
              value: "{{ tpl .Values.licenseKey . }}"
            # TLC_OBJECT_SERVICE_AUTH_SECRET is required for 3LC to run when deployed in enterprise settings.
            # This should be a strong, random string that you come up with that is known only to the Dashboard and Object Service.
            # This can also be configured as a Kubernetes secret for more security. For the sake of the demo, a Kubernetes secret is not used.
            # See also: https://docs.3lc.ai/3lc/latest/getting-started/deployment-options/enterprise-on-prem/secure-communication.html
            - name: TLC_OBJECT_SERVICE_AUTH_SECRET
              value: "{{ tpl .Values.objectServiceAuthSecret . }}"
            # TLC_PROJECT_ROOT_URL can be configured to provide the location where 3LC projects are stored.
            # For this demo, the volume is mounted as /data from the host file system (./mounts/3lc) so that we can see the projects being saved to the current folder.
            - name: TLC_PROJECT_ROOT_URL
              value: "/data/3lc/project"
      volumes:
        - name: my-volume
          hostPath:
            path: {{ tpl .Values.pvc_host_path . }}
            type: DirectoryOrCreate
        
          
